---
title: "mRNA vs lncRNA TR binding"
output: html_document
editor_options: 
  chunk_output_type: console
---
``` {r setup, include=FALSE}
options(stringsAsFactors = FALSE)
knitr::opts_chunk$set(echo = TRUE)
source("/Shares/rinn_class/data/k562_chip/analysis/util/intersect_functions.R")
source("/Shares/rinn_class/data/k562_chip/analysis/util/_setup.R")
library(GenomicRanges)
library(tidyverse)
library(effectsize)
library(regioneR)
```

```{r}
# Import peaks
peak_list <- import_peaks("/Shares/rinn_class/data/CLASS_2020/analysis/01_consensus_peaks/results/")
# Import gencode
gencode_gr <- rtracklayer::import("/Shares/rinn_class/data/genomes/human/gencode/v32/gencode.v32.annotation.gtf")
lncrna_promoters <- get_promoter_regions(gencode_gr, biotype = "lncRNA")
mrna_promoters <- get_promoter_regions(gencode_gr, biotype = "protein_coding")
lncrna_matrix <- count_peaks_per_feature(lncrna_promoters, peak_list, type = "occurence")
mrna_matrix <- count_peaks_per_feature(mrna_promoters, peak_list, type = "occurence")
```

```{r}

# lncrna promoter occupancy 


lncrna_num_overlaps <- rowSums(lncrna_matrix)
mrna_num_overlaps <- rowSums(mrna_matrix)
num_peaks <- sapply(peak_list, length)
total_lncrna <- length(lncrna_promoters)
total_mrna <- length(mrna_promoters)
total_genes <- total_lncrna + total_mrna
chisq_res <- data.frame("tf" =character(),
                        "lncrna_peaks_observed" = numeric(),
                        "chisq_stat" = numeric(),
                        "chisq_pval" = numeric(),
                        "lncrna_peaks_expected" = numeric())
for(i in 1:length(num_peaks)) {
  total_peaks <- num_peaks[[i]]
  df1 <- data.frame("gene_type" = c("lncRNA","lncRNA", "mRNA", "mRNA"),
                    "promoter_bound" = c("bound", "not_bound", "bound", "not_bound"),
                    "count" = c(lncrna_num_overlaps[[i]],
                                total_lncrna - lncrna_num_overlaps[[i]],
                                mrna_num_overlaps[[i]],
                                total_mrna - mrna_num_overlaps[[i]])) %>%
    pivot_wider(names_from = gene_type, values_from = count) %>%
    column_to_rownames("promoter_bound") %>%
    as.matrix()
  
  csres <- chisq.test(df1)
  
  # TODO add phi calculation; r package effectsize 
  
  phi_coef <- phi(df1)
  
  tdf <- data.frame("tf" = names(num_peaks[i]),
                    "lncrna_peaks_observed" = lncrna_num_overlaps[[i]],
                    "chisq_stat" = csres$statistic,
                    "chisq_pval" = csres$p.value,
                    "lncrna_peaks_expected" = csres$expected[1,1],
                    "phi_coefficient" = phi_coef$phi)
  chisq_res <- bind_rows(chisq_res, tdf)
}

chisq_res$padj <- p.adjust(chisq_res$chisq_pval, method = "BH")
chisq_res$diff <- chisq_res$lncrna_peaks_observed - chisq_res$lncrna_peaks_expected
write_csv(chisq_res, "results/lncrna_vs_mrna_chisq_results.csv")

# full lncRNA promoter occupancy plot
g <- ggplot(chisq_res, aes(x = diff, y = -log10(chisq_pval) ))
g + geom_point() + geom_smooth() 


# zoom in plot 
g2 <- ggplot(chisq_res, aes(x = diff, y = -log10(chisq_pval) ))
g2 + geom_point() + geom_smooth()  + xlim(-35, 35) + ylim(0, 5)  + geom_text(data = subset(chisq_res, diff > 0), aes(diff, -log10(chisq_pval), label = tf, check_overlap = TRUE))





#ggsave("figures/pvalue_vs_phi.png")

# contingency table
# lncRNA yes lncRNA no
# tf bound
# tf not bound
```

``` {r}

# mrna promoter occupancy chisquared


lncrna_num_overlaps <- rowSums(lncrna_matrix)
mrna_num_overlaps <- rowSums(mrna_matrix)
num_peaks <- sapply(peak_list, length)
total_lncrna <- length(lncrna_promoters)
total_mrna <- length(mrna_promoters)
total_genes <- total_lncrna + total_mrna
chisq_res2 <- data.frame("tf" =character(),
                        "lncrna_peaks_observed" = numeric(),
                        "chisq_stat" = numeric(),
                        "chisq_pval" = numeric(),
                        "lncrna_peaks_expected" = numeric())

for(i in 1:length(num_peaks)) {
  total_peaks <- num_peaks[[i]]
  df1 <- data.frame("gene_type" = c("lncRNA","lncRNA", "mRNA", "mRNA"),
                    "promoter_bound" = c("bound", "not_bound", "bound", "not_bound"),
                    "count" = c(lncrna_num_overlaps[[i]],
                                total_lncrna - lncrna_num_overlaps[[i]],
                                mrna_num_overlaps[[i]],
                                total_mrna - mrna_num_overlaps[[i]])) %>%
    pivot_wider(names_from = gene_type, values_from = count) %>%
    column_to_rownames("promoter_bound") %>%
    as.matrix()
  
  csres <- chisq.test(df1)
  
  # TODO add phi calculation; r package effectsize 
  #  phi_coef <- phi(df1)
  
  tdf2 <- data.frame("tf" = names(num_peaks[i]),
                    "lncrna_peaks_observed" = lncrna_num_overlaps[[i]],
                    "chisq_stat" = csres$statistic,
                    "chisq_pval" = csres$p.value,
                    "lncrna_peaks_expected" = csres$expected[1,1],
                    "mrna_peaks_observed" = mrna_num_overlaps[[i]],
                    "mrna_peaks_expected" = csres$expected[1,2])
  chisq_res2 <- bind_rows(chisq_res2, tdf2)
}


chisq_res2$padj <- p.adjust(chisq_res2$chisq_pval, method = "BH")
chisq_res2$diff <- chisq_res2$mrna_peaks_observed - chisq_res2$mrna_peaks_expected
# write_csv(chisq_res, "results/lncrna_vs_mrna_chisq_results.csv")

# full mRNA promoter occupancy plot
g3 <- ggplot(chisq_res2, aes(x = diff, y = -log10(chisq_pval) ))
g3 + geom_point() + geom_smooth() 


# zoom in plot 
g4 <- ggplot(chisq_res2, aes(x = diff, y = -log10(chisq_pval) ))
g4 + geom_point() + geom_smooth()  + xlim(-35, 35) + ylim(0, 5)  + geom_text(data = subset(chisq_res2, diff > 0), aes(diff, -log10(chisq_pval), label = tf, check_overlap = TRUE))





#ggsave("figures/pvalue_vs_phi.png")

# contingency table
# lncRNA yes lncRNA no
# tf bound
# tf not bound

```

``` {r}
# plot mrna vs lncrna somehow

# g5 <- ggplot(chisq_res2, aes(x = diff, y = -log10(chisq_pval)))
# g6 <- ggplot(chisq_res, aes(x = diff, y = -log10(chisq_pval)))
# g5 <- bind_rows(g5, g6)
# g5 + g6 + geom_point() + geom_smooth()

```

