---
title: 'Permutation test: pre-calculate permutations'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(stringsAsFactors = FALSE)
library(tidyverse)
library(GenomicRanges)
library(rslurm)
library(regioneR)
source("../util/intersect_functions.R")
source("../util/_setup.R")
```


```{r import}
peak_list <- import_peaks("/Shares/rinn_class/data/k562_chip/analysis/00_consensus_peaks/results/")

gencode_gr <- rtracklayer::import("/Shares/rinn_class/data/genomes/human/gencode/v32/gencode.v32.annotation.gtf")
lncrna_promoters <- get_promoter_regions(gencode_gr, biotype = "lncRNA")
mrna_promoters <- get_promoter_regions(gencode_gr, biotype = "protein_coding")


rmsk <- import_repeatmasker()
rmsk_family <- subset_rmsk(rmsk, rep_level = "family")
names(rmsk_family) <- paste(names(rmsk_family), "family", sep = "_")
rmsk_class <- subset_rmsk(rmsk, rep_level = "class")
names(rmsk_class) <- paste(names(rmsk_class), "class", sep = "_")


region_list <- c("lncrna_promoters" = list(lncrna_promoters), 
                 "mrna_promoters" = list(mrna_promoters), 
                 rmsk_family, rmsk_class)



canonical_chr <- as.character(unique(seqnames(region_list[[1]])))
# sanitize region list
for(i in 1:length(region_list)) {
  region_list[[i]] <- region_list[[i]][which(seqnames(region_list[[i]]) %in% canonical_chr)]
}
```


```{r}
genome <- tibble::tribble(
~chrom, ~size,
"chr1",	248956422,
"chr2",	242193529,
"chr3",	198295559,
"chr4",	190214555,
"chr5",	181538259,
"chr6",	170805979,
"chr7",	159345973,
"chr8",	145138636,
"chr9",	138394717,
"chr10",	133797422,
"chr11",	135086622,
"chr12",	133275309,
"chr13",	114364328,
"chr14",	107043718,
"chr15",	101991189,
"chr16",	90338345,
"chr17",	83257441,
"chr18",	80373285,
"chr19",	58617616,
"chr20",	64444167,
"chr21",	46709983,
"chr22",	50818468,
"chrX",	156040895,
"chrY",	57227415,
"chrM",	16569
)
write_csv(genome, "chr_sizes.csv")
is.tbl_genome(genome)
genome <- tbl_genome(genome)
is.tbl_genome(genome)

```


```{r}
# Let's make a save some permutations

rlist <- lapply(region_list, as.tbl_interval)
plist <- lapply(peak_list, as.tbl_interval)
region_set <- plist[[1]]
nperms <- 100
plist2 <- plist[1:4]
object.size(plist2)

as.numeric(object.size(peak_list_nulls))/as.numeric(object.size(plist2))
as.numeric(object.size(plist))*835/1e9

# Hmm, the whole peak list will be ~60-70 GB.
# The whole region list will be 430GB
# We could of course do one region at a time.
as.numeric(object.size(rlist))*835/1e9

peak_list_nulls <- lapply(plist2, make_permutations, nperms = 1000)
make_permutations <- function(region_set, nperms) {
  set.seed(12393)
  cat("Creating permutations\n")
  perms <- lapply(1:nperms, function(x) {
    bed_shuffle(x = region_set, genome = genome) })
  return(perms)
}

library(valr)
library(rbenchmark)
bm <- benchmark("regioner" = randomizeRegions(mrna_promoters, genome = "hg38"),
                "valr" = bed_shuffle(mrnaprom, genome),
                replications = 10)
# Apparently all the metadata gets stripped here.
# mrna_promoters@elementMetadata$name <- "huh"nrow(bed_intersect(mrnaprom, hmm)
mrnaprom <- as.tbl_interval(mrna_promoters)
mrnaprom$feature_group <- "mrna"

lncrnaprom <- as.tbl_interval(lncrna_promoters)
lncrnaprom$feature_group <- "lncrna"

proms <- bind_rows(mrnaprom, lncrnaprom)


mrnaprom$width <- mrnaprom$end - mrnaprom$start
bs1 <- bed_shuffle(mrnaprom, genome)
bs2 <- bed_shuffle(mrnaprom, genome)
bs1$shuf <- 1
bs2$shuf <- 2
bs <- bind_rows(bs1, bs2)
bed_map(mrnaprom, hmm,  .counts = dplyr::n())

bed_projection(mrnaprom, hmm, genome)

nrow(bed_intersect(mrnaprom, bs %>% filter(shuf == 2)))
countOverlaps()
?bed_map
huh <- randomizeRegions(mrna_promoters, genome = "hg38")
bm2 <- benchmark("gr" = numOverlaps(mrna_promoters, huh),
                 "bs" = nrow(bed_intersect(mrnaprom, hmm)))

bed_shuffle(mrnaprom, genome)
rr <- lapply(1:100, function(x) { randomizeRegions(mrna_promoters, genome = "hg38") })
results <- microbenchmark(  
  read.csv2.test = lapply(csv.files, read.csv2),
  read_csv.test  = lapply(csv.files, read_csv),
  times = 50)
pval <- (sum(orig.ev <= rand.ev, na.rm=TRUE) + 1) / (num.valid.values + 1)
zscore <- round((orig.ev - mean(rand.ev, na.rm=TRUE)) / stats::sd(rand.ev, na.rm=TRUE), 4)


```



