---
title: "repeat_family_heatmap"
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```
```{r}
# Read in the results of the permutation test.
# The key columns here are the region (repeat family) and the tf and the observed peaks and the zscore
# The observed column has the number of peaks that overlapped
# The zscore is based on the mean and std dev of the permuted overlaps. (If the zscore is high, then the number of observed peaks is more than expected base on the permuted null distribution)
# We'll plot the zscore in a heatmap.
permutation_results_families <- read_csv("/Shares/rinn_class/data/k562_chip/analysis/11_peak_feature_intersect/results/permutation_results_repeat_families.csv") %>%
  filter(zscore != Inf)
permutation_results_classes <- read_csv("/Shares/rinn_class/data/k562_chip/analysis/11_peak_feature_intersect/results/permutation_results_repeat_classes.csv")%>%
  filter(zscore != Inf)
```
```{r}
# It's easy to make a heatmap here FOR CLASSES.
g <- ggplot(permutation_results_classes, aes(x = tf, y = region, fill = zscore))
g + geom_raster() + scale_fill_gradient2() + coord_flip() + 
  theme(axis.text.x = element_text(angle = 90L, hjust = 1L, vjust = 0.5))
# But you should to cluster the rows and columns.
# Right now they're ordered by alphanumeric order
# The will only be plotted in the order you want if you make the tf and region columns into factors.
# Here's an example
class_ov_matrix <- permutation_results_classes %>%
  dplyr::select(tf, region, zscore) %>%
  pivot_wider(names_from = tf, values_from = zscore) %>%
  column_to_rownames("region") %>%
  as.matrix()
region_clust <- hclust(dist(class_ov_matrix))
plot(region_clust)
tf_clust <- hclust(dist(t(class_ov_matrix)))
plot(tf_clust)
# Now let's factorize these columns according to the order which we specified
permutation_results_classes$region <- factor(permutation_results_classes$region, region_clust$labels[region_clust$order])
permutation_results_classes$tf <- factor(permutation_results_classes$tf, tf_clust$labels[tf_clust$order])
# And then we can plot it again
g <- ggplot(permutation_results_classes, aes(x = tf, y = region, fill = zscore))
g + geom_raster() + scale_fill_gradient2() + coord_flip() + 
  theme(axis.text.x = element_text(angle = 90L, hjust = 1L, vjust = 0.5))
ggsave("repeat_classes_vs_tf_peaks.pdf", height = 28, width = 5)
```

```{r}
# FOR FAMILIES.
g <- ggplot(permutation_results_families, aes(x = tf, y = region, fill = zscore))
g + geom_raster() + scale_fill_gradient2() + coord_flip() + 
  theme(axis.text.x = element_text(angle = 90L, hjust = 1L, vjust = 0.5))
# But you should to cluster the rows and columns.
# Right now they're ordered by alphanumeric order
# The will only be plotted in the order you want if you make the tf and region columns into factors.
# Here's an example
class_ov_matrix <- permutation_results_families %>%
  dplyr::select(tf, region, zscore) %>%
  pivot_wider(names_from = tf, values_from = zscore) %>%
  column_to_rownames("region") %>%
  as.matrix()
region_clust <- hclust(dist(class_ov_matrix))
plot(region_clust)
tf_clust <- hclust(dist(t(class_ov_matrix)))
plot(tf_clust)
# Now let's factorize these columns according to the order which we specified
permutation_results_families$region <- factor(permutation_results_families$region, region_clust$labels[region_clust$order])
permutation_results_families$tf <- factor(permutation_results_families$tf, tf_clust$labels[tf_clust$order])
# And then we can plot it again
g <- ggplot(permutation_results_families, aes(x = tf, y = region, fill = zscore))
g + geom_raster() + scale_fill_gradient2() + coord_flip() + 
  theme(axis.text.x = element_text(angle = 90L, hjust = 1L, vjust = 0.5))
ggsave("repeat_families_vs_tf_peaks.pdf", height = 28, width = 5)
```

```{r}
# TODO: You can run the same for families. DONE
# TODO: To make this cleaner, let's only plot those rows and columns (TFs and regions) which have padj < 0.05
# For example:
sig_tfs <- permutation_results_classes[which(permutation_results_classes$padj < 0.05), "tf"]
sig_tfs <- unique(as.character(sig_tfs$tf))
sig_regions <- permutation_results_classes[which(permutation_results_classes$padj < 0.05), "region"]
sig_regions <- unique(as.character(sig_regions$region))
sig_classes_subset <- permutation_results_classes %>%
  filter(tf %in% sig_tfs,
         region %in% sig_regions)
```
