---
title: "march6-hw.rmd"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(IRanges)
library(GenomicRanges)
library(rtracklayer)
library(ggplot2)
library(readr)
library(stringr)
library(tibble)
```

```{r}
# read in a file and make it a GRange object
get_grange <-function(filepath){
  data = read.table(filepath)
  gr <- GRanges(seqnames = data$V1,
                    ranges = IRanges(start=data$V2,end=data$V3))
  return(gr)
}

# take 2 GRange objects, find the common peaks, returns the common peaks as a GRanges object
filter_grs <-function(gr1,gr2){
  # take two grs, find the over lap
  # re turn portions of the GRs that were in the overlap
  ol <- GenomicRanges::findOverlaps(gr1,gr2)
  grb <- gr1[unique(ol@from)]
  # return only 1 because they should be the same from here on
  return(grb)
}
# returns a GRanges object of the common peaks for the given files also writes the common peaks to a bed file
get_common_peaks_in_TF <- function(files,tf){
  print(paste('TF:',tf))
  main <- get_grange(files[1])
  for(i in 2:length(files)){
    main <- filter_grs(main,get_grange(files[[i]]))
  }
  
  #make a data frame of the info
  # get the names of the chromosomes / unmapped scaffolds
  region_names <- as.character(main@seqnames@values)
  # get the number of repeats of each of the afore found regions
  region_lengths <- main@seqnames@lengths
  # make a vector of region names repeated the correct number of times
  regions <- c()
  print(paste('replicate:',length(region_lengths),length(region_names)))
  if(length(region_lengths) > 0 & length(region_names) > 0){
    for(i in seq(length(region_lengths))){
      regions <- c(regions,replicate(region_lengths[i],region_names[i]))
    }
  }else{
    print(paste('skipping:',tf))
    # after I ran this it skipped two TFs
    # MCM2 and TRIM25
    return(NULL)
  }
  bed <- tibble('chromosome'=regions,
                        'source'=replicate(length(regions),tf),
                        'start'=main@ranges@start,
                      'width'=main@ranges@width,
                      'end'=(main@ranges@start + main@ranges@width))
  #write this one to a bed file
  write_tsv(bed,paste('/scratch/Users/mibr6115/TFS/',tf,'.bed',sep=''))
  return(main)
}
```

```{r}
do_all_tfs <-function(){
  path <- '/Shares/rinn_class/data/k562_chip/results/bwa/mergedLibrary/macs/broadPeak/'
  # get all files
  files <- list.files(path)
  # get just the broadpeaks ones
  peakfiles <- c()
  tfs <- c()
  # loop over all files
  for(i in seq(1,length(files))){
    #check if it is a peak file
    if(str_detect(files[[i]],'broadPeak')){
      # add the peak files to the vector of peak files
      peakfiles <- c(peakfiles,files[[i]])
      # do some REXEG voodoo to get jus the TF name from the file names
      tfs <- c(tfs,str_replace(str_extract(files[[i]],'\\w+_R'),'_R',''))
    }
  }
  print(peakfiles)
  tfs <- unique(tfs)
  for( i in seq(1,length(tfs))){
    # get the files relating to this one TF
    tf_files <- c()
    for( j in seq(1,length(peakfiles))){
      if(str_detect(peakfiles[[j]],tfs[[i]])){
        tf_files <- c(tf_files,paste(path,peakfiles[[j]],sep=''))
      }
    }
    print('-----------------')
    print(tf_files)
    # find all peaks in common among replicates of this TF and write them to a bed file
    get_common_peaks_in_TF(tf_files,tfs[[i]])
  }
}
do_all_tfs()
```



