---
title: "Gene_profile_deep_tools"
author: "MS & JR"
date: "2/25/2020"
output: html_document
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(stringsAsFactors = FALSE)
library(rtracklayer)
library(GenomicFeatures)
library(tidyverse)
```

```{r}
#Cool way to load a bunch of files into a list and then a for loop to do the same for all files and the bind them at the end
fl <- list.files("/Shares/rinn_class/data/k562_chip/results/bwa/mergedLibrary/deepTools/plotProfile/", full.names=TRUE)
fl <- fl[grep(".tab", fl)]
dat <- read.table(fl[1], skip=1)
for(i in 2:length(fl)) {
  tdat <- read.table(fl[i], skip = 1)
  dat <- bind_rows(dat, tdat)
}
samnames <- sapply(fl, function(x) {
tempstring <- unlist(strsplit(x, "//"))[2]
temsprting <- gsub(".plotProfile.tab", "" , tempstring)
return(tempstring)
})
dat$sampnames <- samnames
dat <- dat %>% select(sampnames, everything())
colnames(dat)
dat_long <- gather(dat, key = "position", value = "value", 3:702)
dat_long$position <- gsub("X","",dat_long$position) %>% as.numeric()
dat_long$bp_position <- dat_long$position * 10
dat_long$tf_name <- sapply(dat_long$sampnames, function(x) {
  unlist(strsplit(x, "_"))[[1]]
})
qplot(x=position, y=value, data=dat_long %>% filter(tf_name == "AFF1"), geom=c("point", "smooth"),
      color = sampnames)
g <- ggplot(dat_long %>% filter(tf_name %in% c("DDX20", "AFF1")), aes(x = bp_position, y = value, color = sampnames))
g + geom_line() +
  scale_x_continuous(breaks = seq(0,7000, by = 1000),
                     labels = c("-3000", "-2000", "-1000",
                                "TSS", "TES", "1000", "2000", "3000"))
#prof <- read.table("../../results/bwa/mergedLibrary/deepTools/plotProfile/", header=FALSE, skip=3) #This gets us to the third row as the first two are not values
```

## Clustering

```{r}
# First we're going to average the profile per tf.
dat_sum <- dat_long %>% group_by(tf_name, bp_position) %>%
  summarize(mean_value = mean(value)) %>%
  spread(bp_position, mean_value) %>%
  column_to_rownames(var = "tf_name") %>%
  as.matrix()
dat_sum_long <- dat_long %>% group_by(tf_name, bp_position) %>%
  summarize(mean_value = mean(value))
dat_dist <- dist(dat_sum, method = "euclidean")
dat_hclust <- hclust(dat_dist)
plot(dat_hclust)
# Some example plots
g <- ggplot(dat_sum_long %>% filter(tf_name %in% c("eGFP-ZNF512", "HDAC3")),
            aes(x = bp_position, y = mean_value, color = tf_name))
g + geom_line() +
  scale_x_continuous(breaks = seq(0,7000, by = 1000),
                     labels = c("-3000", "-2000", "-1000",
                                "TSS", "TES", "1000", "2000", "3000"))
```

## Z-scaled clustering

```{r}
# First we're going to average the profile per tf.
dat_sum <- dat_long %>% group_by(tf_name, bp_position) %>%
  summarize(mean_value = mean(value)) %>%
  spread(bp_position, mean_value) %>%
  column_to_rownames(var = "tf_name") %>%
  as.matrix()
dat_sum_long <- dat_long %>% group_by(tf_name, bp_position) %>%
  summarize(mean_value = mean(value))

dat_norm <- t(scale(t(dat_sum)))
dat_dist <- dist(dat_norm, method = "euclidean")
dat_hclust <- hclust(dat_dist)
plot(dat_hclust)
# Some example plots
g <- ggplot(dat_sum_long %>% filter(tf_name %in% c("eGFP-ZNF512", "HDAC3")),
            aes(x = bp_position, y = mean_value, color = tf_name))
g + geom_line() +
  scale_x_continuous(breaks = seq(0,7000, by = 1000),
                     labels = c("-3000", "-2000", "-1000",
                                "TSS", "TES", "1000", "2000", "3000"))
clust <- cutree(dat_hclust, k = 7)
clust_df <- data.frame("tf_name" = rownames(dat_norm),
                       "clust" = clust)
```
