---
title: "Clustering by Features"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
options(stringsAsFactors = FALSE)
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(GenomicRanges)
source("../util/intersect_functions.R")
source("../util/_setup.R")
```


The first step is to get a matrix of features by TFs.

```{r}
peak_list <- import_peaks("/Shares/rinn_class/data/k562_chip/analysis/00_consensus_peaks/results/")
gencode_gr <- rtracklayer::import("/Shares/rinn_class/data/genomes/human/gencode/v32/gencode.v32.annotation.gtf")
promoters <- get_promoter_regions(gencode_gr, biotype = c("lncRNA", "protein_coding"))

promoter_peak_count <- count_peaks_per_feature(promoters, peak_list)

# Remove columns with no TF binding
promoter_peak_count <- promoter_peak_count[,which(colSums(promoter_peak_count) > 0)]

# Remove TFs with no promoter peaks
no_promoter_binding <- rownames(promoter_peak_count)[which(rowSums(promoter_peak_count) == 0)]
promoter_peak_count <- promoter_peak_count[which(rowSums(promoter_peak_count) > 0),]

# Make this binary -- make it a co-occurence matrix.
promoter_peak_occurence <- matrix(as.numeric(promoter_peak_count > 0), 
                           nrow = dim(promoter_peak_count)[1],
                           ncol = dim(promoter_peak_count)[2])
rownames(promoter_peak_occurence) <- rownames(promoter_peak_count)
colnames(promoter_peak_occurence) <- colnames(promoter_peak_count)
```


```{r}
# Calculate a distance measure between the rows.
library(jaccard)

bin_hier <- hclust(dist(promoter_peak_occurence, method = "binary"))
plot(bin_hier)
# bin_hier_bins <- cutree(bin_hier, k = 10)
library(ggdendro)

ggdendro::ggdendrogram(bin_hier, rotate = TRUE,  size = 2)
ggsave("hclust_binary_dist.pdf", height = 26, width = 6)

hclust_euc <- hclust(dist(promoter_peak_occurence, method = "euclidean"))
ggdendro::ggdendrogram(hclust_euc, rotate = TRUE,  size = 2)
ggsave("hclust_euclidean_dist.pdf", height = 26, width = 6)
```

```{r}
lncrna_promoters <- get_promoter_regions(gencode_gr, biotype = "lncRNA")
mrna_promoters <- get_promoter_regions(gencode_gr, biotype = "protein_coding")


lncrna_peak_occurence <- count_peaks_per_feature(lncrna_promoters, peak_list, type = "occurence")
# Remove columns with no TF binding
lncrna_peak_occurence <- lncrna_peak_occurence[,which(colSums(lncrna_peak_occurence) > 0)]

# Remove TFs with no promoter peaks
lncrna_no_promoter_binding <- rownames(lncrna_peak_occurence)[which(rowSums(lncrna_peak_occurence) == 0)]
lncrna_peak_occurence <- lncrna_peak_occurence[which(rowSums(lncrna_peak_occurence) > 0),]


mrna_peak_occurence <- count_peaks_per_feature(mrna_promoters, peak_list, type = "occurence")
# Remove columns with no TF binding
mrna_peak_occurence <- mrna_peak_occurence[,which(colSums(mrna_peak_occurence) > 0)]

# Remove TFs with no promoter peaks
mrna_no_promoter_binding <- rownames(mrna_peak_occurence)[which(rowSums(mrna_peak_occurence) == 0)]
mrna_peak_occurence <- mrna_peak_occurence[which(rowSums(mrna_peak_occurence) > 0),]



lncrna_hier <- hclust(dist(lncrna_peak_occurence, method = "binary"))
ggdendro::ggdendrogram(lncrna_hier, rotate = TRUE,  size = 2)
ggsave("lncrna_hclust_binary_dist.pdf", height = 26, width = 6)

mrna_hier <- hclust(dist(mrna_peak_occurence, method = "binary"))
ggdendro::ggdendrogram(mrna_hier, rotate = TRUE,  size = 2)
ggsave("mrna_hclust_binary_dist.pdf", height = 26, width = 6)
```


```{r}
tf_df <- data.frame(type = "lncRNA", 
                    tf = rownames(lncrna_peak_occurence),
                    binding_events = rowSums(lncrna_peak_occurence),
                    total_promoters = ncol(lncrna_peak_occurence))
tf_df <- bind_rows(tf_df,
                   data.frame(type = "mRNA", 
                    tf = rownames(mrna_peak_occurence),
                    binding_events = rowSums(mrna_peak_occurence),
                    total_promoters = ncol(mrna_peak_occurence)))
tf_df$fraction_bound <- tf_df$binding_events / tf_df$total_promoters

tf_dfw <- tf_df %>%
  dplyr::select(tf, type, fraction_bound) %>%
  pivot_wider(names_from = type, values_from = fraction_bound, values_fill = 0)
tf_dfw[is.na(tf_dfw$lncRNA), "lncRNA"] <- 0

library(ggrepel)
g <- ggplot(tf_dfw, aes(x = mRNA, y = lncRNA, label = tf))
g + geom_point() +
  geom_abline(slope = 1, lty = 2) + 
  geom_smooth(method = "lm", se = F) + 
  geom_text()
  # geom_text_repel(data = tf_dfw %>% sample_n(10)) + 
  # geom_text_repel(data = tf_dfw %>% filter(mRNA> 0.55))

lncRNA_frac <- tf_dfw$lncRNA
mRNA_frac <- tf_dfw$mRNA
names(lncRNA_frac) <- tf_dfw$tf
names(mRNA_frac) <- tf_dfw$tf


tflm <- lm(lncRNA_frac ~ mRNA_frac)

tf_dfw$resid <- tflm$residuals
tf_dfw$pred <- predict(tflm)

g <- ggplot(tf_dfw, aes(x = mRNA, y = lncRNA, label = tf))
g + geom_point() +
  geom_abline(slope = 1, lty = 2) + 
  geom_smooth(method = "lm", se = F) + 
  geom_text() + 
  geom_point(aes(x = mRNA, y = predict), color = "red")


tf_dfw$norm_resid <- tf_dfw$resid / tf_dfw$pred
g <- ggplot(tf_dfw, aes(x = pred, y = norm_resid, label = tf))
g + 
  geom_hline(yintercept = 0) +
  geom_point() +
  geom_text()


g <- ggplot(tf_dfw, aes(x = norm_resid))
g + geom_density()

tf_dfw$z <- scale(tf_dfw$norm_resid)
g <- ggplot(tf_dfw, aes(x = pred, y = z, label = tf))
g + 
  geom_hline(yintercept = 0) +
  geom_point() +
  geom_text() 

# wilcox.test(lncRNA_frac~mRNA_frac)

g <- ggplot(tf_dfw, aes(x = z))
g + geom_density()
```




