---
title: "simple_regression"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
options(stringsAsFactors = FALSE)
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(broom)
library(ggpubr)
```

```{r}
dbp_occurence_matrix <- read.table("../01_consensus_peaks/results/lncrna_mrna_promoter_peak_occurence_matrix.tsv")

rnaseq_exp <- read_csv("../05_rnaseq_expression/results/k562_tpm.csv")
nascent_exp <- read_csv("../06_nascent_expression/results/k562_nascent_tpm.csv")
names(rnaseq_exp)[3] <- "rnaseq_tpm"
names(nascent_exp)[3] <- "nascent_tpm"
exp <- merge(rnaseq_exp, nascent_exp)


```

RNA-seq vs Nascent

```{r}
g <- ggplot(exp, aes(x = log10(rnaseq_tpm), y = log10(nascent_tpm)))
g + geom_point() + stat_cor()
```

```{r}
occ_df <- t(dbp_occurence_matrix) %>%
  as.data.frame() %>%
  rownames_to_column("gene_id")
occ_df <- merge(exp %>% dplyr::select(gene_id, nascent_tpm, rnaseq_tpm), occ_df) %>%
  column_to_rownames("gene_id")


lmdf <- data.frame("term" = character(),
                   "estimate" = numeric(),
                   "std.error" = numeric(),
                   "statistic" = numeric(),
                   "p.value" = numeric(),
                   "type" = character(),
                   "dbp" = character())
for(i in 3:ncol(occ_df)) {
  nt_lmdf <- tidy(lm(occ_df$nascent_tpm ~ occ_df[,i]))
  nt_lmdf$type <- "nascent"
  rt_lmdf <- tidy(lm(occ_df$rnaseq_tpm ~ occ_df[,i]))
  rt_lmdf$type <- "rnaseq"
  t_lmdf <- bind_rows(nt_lmdf, rt_lmdf)
  t_lmdf$dbp <- colnames(occ_df)[i]
  lmdf <- bind_rows(lmdf, t_lmdf)
}

lmdf_slopes <- lmdf %>% filter(term != "(Intercept)")
lmdf_slopes$padj <- p.adjust(lmdf_slopes$p.value, method = "BH")

lmdf_slopes_w <- lmdf_slopes %>% dplyr::select(estimate, padj, type, dbp) %>%
  pivot_wider(names_from = type, values_from = c(estimate, padj))



g <- ggplot(lmdf_slopes_w, aes(x = estimate_nascent, y = estimate_rnaseq, label = dbp))
g + geom_point() +
  geom_text()

g <- ggplot(lmdf_slopes_w, aes(x = estimate_rnaseq, y = -log10(padj_rnaseq), label = dbp))
g + geom_point() +
  geom_text()

g <- ggplot(lmdf_slopes_w, aes(x = estimate_nascent, y = -log10(padj_nascent), label = dbp))
g + geom_point() +
  geom_text()

```

