---
title: "Reservoir overlaps with annotated superenhancers"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
options(stringsAsFactors = FALSE)
knitr::opts_chunk$set(echo = TRUE)
library(rtracklayer)
library(liftOver)
library(tidyverse)
library(GenomicRanges)
library(rslurm)
library(regioneR)
```

# Retrieving superenhancer info

We got this from the SEdb: https://asntech.org/dbsuper/

`wget http://asntech.org/dbsuper/data/bed/hg19/K562.bed`

```{r}
reservoirs <- rtracklayer::import("/Shares/rinn_class/data/CLASS_2020/analysis/04_correlation_with_expression/results/k562_ghost_promoters.bed")
se_hg19 <- rtracklayer::import("K562.bed")
ch <- import.chain("hg19ToHg38.over.chain")
```

`http://hgdownload.cse.ucsc.edu/goldenpath/hg19/liftOver/hg19ToHg38.over.chain.gz`  
`gunzip hg19ToHg38.over.chain.gz`

```{r}
seqlevelsStyle(se_hg19) <- "UCSC"  # necessary
se_hg38 <- liftOver(se_hg19, ch)
# Subset just to contiguously liftedOver regions
se_hg38 <- se_hg38[sapply(width(se_hg38), length) == 1]
rtracklayer::export(se_hg38, "results/k562_superenhancers_hg38.bed")
```

```{r}
se_hg38 <- rtracklayer::import("/Shares/rinn_class/data/CLASS_2020/analysis/07_reservoirs/results/k562_superenhancers_hg38.bed")
```

Look at the overlaps between reservoirs and superenhancers:

```{r}
se_res_ov <- findOverlaps(reservoirs, se_hg38)
reservoirs_overlapping_ses <- reservoirs[se_res_ov@from]
rtracklayer::export(reservoirs_overlapping_ses, "results/reservoirs_overlapping_ses.bed")
```

Do permutation of superenhancers to see how often they overlap with reservoirs by chance:

```{r}
hg38 <- getGenome("hg38")
pt <- overlapPermTest(A = reservoirs, 
                        B = se_hg38, 
                        ntimes = 1000, 
                        non.overlapping = FALSE, 
                        verbose = FALSE,
                        genome = hg38,
                        alternative =  "auto", 
                        mc.cores = 20)
plot(pt)
```

